# version: '3.8'
# services:
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: 1234
#       MYSQL_DATABASE: spring_react
#     ports:
#       - "3307:3306"
#     networks:
#       - my-network

#   app:
#     image: my-app:latest
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       MYSQL_HOST: db
#       MYSQL_PORT: 3306
#       MYSQL_DATABASE: spring_react
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 1234
#     depends_on:
#       - db
#     ports:
#       - "8080:8080"
#     networks:
#       - my-network

# networks:
#   my-network:
